config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'pages/home'

  get 'pages/dashboard'

  root to: 'pages#home'

  resources :cars do
    resources :bookings, only: [:show, :new, :create, :destroy]
  end
  resources :dashboard, only: [:index]

end

app/models/address.rb
class Address < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :car
  accepts_nested_attributes_for :car
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  validates_presence_of :car_id
  validates_presence_of :user_id
 # validates_uniqueness_of :car_id, scope: [:user_id]
  validates_presence_of :checkin_date, :checkout_date


  belongs_to :car
  belongs_to :user
  has_many :reviews
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  validates_presence_of :user_id

  belongs_to :user
  has_many :addresses, dependent: :destroy
  has_many :bookings, dependent: :destroy

  def available?(first_day, last_day)
    output = true
    if self.bookings
      self.bookings.each do |booking|
        booking_intervall(booking)
        if (@booking_dates.include? first_day) || (@booking_dates.include? last_day)
          output = false
          break
        end
      end
    end
    output
  end

  private

  def booking_intervall(booking)
    @booking_dates = []
    day = booking.checkin_date
    while day <= booking.checkout_date do
      @booking_dates << day
      day += 1
    end
    return @booking_dates
  end
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :booking
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :picture,
    styles: { medium: "300x300#", thumb: "100x100#" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :first_name
  validates_presence_of :last_name
  # validates_presence_of :address
  # validates_presence_of :phone_number
  has_many :bookings, dependent: :destroy
  has_many :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters                                                                                 #add address, phone_number
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :picture, :address, :phone_number ) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password, :picture, :address, :phone_number) }
    end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: [:show, :create]

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    # if user_signed_in?
    #   @booking = Booking.new(booking_params)
    #   @booking.car_id = @car.id
    #   @booking.user_id = current_user.id
    #   @booking.save
    #   @car.available = false
    #   @car.save
    #   redirect_to car_booking_path(@car, @booking)
    # else
    #   redirect_to new_user_session_path
    # end

    checkin_date = params[:booking][:checkin_date].to_datetime
    checkout_date = params[:booking][:checkout_date].to_datetime
    @booking = Booking.new(booking_params)
    if @car.available?(checkin_date, checkout_date)
      @booking.car = @car
      @booking.user = current_user
      if @booking.save
        redirect_to car_booking_path(@booking.car, @booking)
      else
        render "cars/show"
      end
    else
      flash[:alert] = "This car is not available on the requested period"
      render "cars/show"
    end


  end
  def edit
  end
  def update
  end
  def destroy
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:checkin_date, :checkout_date, :distance, :car_id)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :update, :edit, :destroy]

  def index

    @place = params[:place]

    if params[:place] != ''
      @page_title = params[:place]
      @addresses = Address.near(params[:place], 15)
      @cars = delete_doubles(@addresses)

      @markers = marker_map(@addresses)
      #raise
    else
      @cars = Car.all
      @addresses = find_car_address(@cars)
      @markers = marker_map(@addresses)
    end

    @ransack_params = params[:q] || {}
    @ransack = Car.ransack(@ransack_params)

    #params[:q] = Rails.cache.read("q")

    if params[:q]

      @cars = @ransack.result(distinct: true).includes(:addresses)

      @addresses = find_car_address(@cars)
      @markers = marker_map(@addresses)

    end
  end

  def show
    @addresses = @car.addresses
    @markers = marker_map(@addresses)
    @booking = Booking.new
  end

  def new
    if user_signed_in?
      @car = Car.new
      @car.addresses.build

    else
      redirect_to new_user_session_path
    end
  end

  def create
    @car = Car.new(car_params)
    @user = User.find(current_user.id)
    @car.user = @user
    @car.save ? (redirect_to car_path(@car)) : (render 'new')
  end

  def edit
    @car.addresses.build
  end

  def update
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:make, :model, :motorisation, :category, :seats, :daily_rate, :description, :year, :gear_box, :doors, :gaz_consumption, :picture, addresses_attributes: [:id, :car_id, :address, :_destroy])
  end

  def set_user
  end

  def marker_map(elements)
    markers = Gmaps4rails.build_markers(elements) do |element, marker|
      marker.lat element.latitude
      marker.lng element.longitude
    end
    return markers
  end

  def find_car_address(cars)
    addresses =  []
      cars.each do |car|
        addresses.push(car.addresses.take)
      end
    return addresses
  end

  def delete_doubles(array_addresses)

    array_cars = []
      # Get rid of the addresses that have several pick up spot for the same car
      #we get an array containing all the unique car_id

      unique_car_id = array_addresses.map{|t| t.car_id}.uniq

      # We need to find the car associated

      unique_car_id.each do |car_id|
        car = Car.find(car_id)
        array_cars.push(car)
      end
      return array_cars
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'

  def index

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @address = Address.near(params[:address], 10)

  end

  def dashboard
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SimpleFormRansackHelper

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/shared/_bookingform.html.erb
<%= simple_form_for ([@car, @booking]) do |f|%>
  <div class="box-booking-container">
    <!-- <h3>Date de début</h3> -->
    <div class="box-booking-date">
      <%= f.input :checkin_date, as: :date, html5: true %>
    </div>
    <h3>Date de fin</h3>
    <div class="box-booking-date">
      <%= f.input :checkout_date, as: :date, html5: true %>
    </div>
    <h3>Kilométrage estimé</h3>
    <div class="box-booking-kilometer">
      <%= f.input :distance, label: false %>
    </div>
  </div>

  <div class="box-price-container">
    <div class="box-price-price text-center">
      <span><%= @car.daily_rate.to_i %>€ </span> / jour
    </div>
  </div>
  <div class="box-price-booking-btn text-center">
    <%= f.button :submit, "Send a request", class:"btn btn-danger" %>
  </div>
<% end %>

app/views/bookings/shared/_new-form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <%= simple_form_for booking do |f|%>
        <%= f.input :checkin_date %>
        <%= f.input :checkout_date %>
        <%= f.button :submit, class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container", style="position:relative;top:150px">
  <div class="row">
    <div class="col-xs-12">
      <h2></i>Merci d'avoir réservé avec DEways!</h2>
      <p>Voici le récapitulatif de votre réservation :</p>
      <div class="booking-content text-center">
        <h3>Booking ticket n°<%= @booking.id %></h3>
        <hr>
        <ul class="list-unstyled">
          <li><strong>Marque : </strong><%= @car.make %></li>
          <li><strong>Modèle : </strong><%= @car.model %></li>
          <li><strong>Places : </strong><%= @car.seats %></li>

          <hr>
          <li><strong>Nombre de jours: </strong><%= ((@booking.checkout_date - @booking.checkin_date).to_i)/86400 %></li>
          <li><strong>Période: </strong>du <%= @booking.checkin_date %> au <%= @booking.checkout_date %>.</li>
          <li><strong>Prix journalier : </strong><%= @car.daily_rate %>€</li>
          <li><strong>Total TTC: </strong><%= ((@booking.checkout_date - @booking.checkin_date).to_i)/86400 * @booking.car.daily_rate %> €</li>
          <hr>
        </ul>
        <span><i class="fa fa-print"></i> print</span>
      </div>
    </div>
  </div>
  <%= link_to "back", car_path(@car) %>
</div>

app/views/cars/_address_fields.html.erb
<div class="nested-fields">
  <div class="inline">

  <%= f.input :address, label: false %>
  <%= link_to_remove_association "X", f, class:"btn btn-danger" %>
    </div>
  <div class="spacer-small"></div>
</div>

app/views/cars/_car_form.html.erb
<div class="container">
  <%= simple_form_for @car do |f| %>
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <h3>Votre voiture</h3>
      <p>Vous l'aimez, vous la chérissez...</p>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h3>Votre voiture</h3>
      <%= f.input :make %>
      <%= f.input :model %>
      <%= f.input :category, collection: ["Citadine", "Berline", "Familiale", "Utilitaire", "Minibus", "4x4", "Cabriolet", "Coupé", "Collection"]%>
      <%= f.input :motorisation, collection: ["Essence", "Diesel", "Hybride", "Electrique", "GPL"] %>
      <%= f.input :year %>
      <%= f.input :gaz_consumption %>
      <%= f.input :gear_box, collection: ["Manuelle", "Automatique", "Séquentielle"] %>
      <%= f.input :seats, collection: 1..10 %>
      <%= f.input :doors, collection: 2..6 %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h3>Tarif de location</h3>
      <%= f.input :daily_rate, label: false, placeholder: "30€" %>
      <h3>Description</h3>
      <%= f.input :description, as: :text, label: false %>
      <h3>Photo</h3>
      <%= f.input :picture, label: false %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h3>Adresses</h3>
      <div id="addresses">
        <%= f.simple_fields_for :addresses do |address| %>
              <%= render 'address_fields', f: address %>
        <% end %>
            <div class="links col-xs-12">
                <%= link_to_add_association 'add address', f, :addresses, class:"btn btn-success form-control" %>
            </div>

      </div>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 text-center">
      <%= f.button :submit, class:"btn video-banner-btn" %>
    </div>
  </div>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('.nested-fields').last().remove();
    });
  <% end %>
<% end %>

app/views/cars/edit.html.erb
<div class="spacer"></div>
<div class="container">
  <h1>Modifiez votre véhicule</h1>
  <%= render 'shared/car_form' %>
</div>

app/views/cars/index.html.erb
<%= content_for(:title) do %>
  <% if @page_title %>
  Cars in <%= @page_title%>
  <% else %>
  All cars
  <% end %>
<% end %>
<%= content_for(:description) do %>
  bla bla bla
<% end %>



<div class="search-results">
  <div class="search-results-list-container col-xs-12 col-sm-7">
    <div class="search-box-container container-fluid no-padding">
      <div class="col-sm-12 no-padding">
        <%= render 'shared/search_box' %>
      </div>
    </div>

    <div class="spacer"></div>

    <div class="container-fluid no-padding">
      <% @cars.each do |car| %>
        <div class="col-sm-12 col-md-6 no-padding">
          <%=  render 'shared/car_card', car: car %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="search-results-map col-xs-12 col-xs-offset-12 col-sm-5 col-sm-offset-7 no-padding" >
    <div class="spacer-nav-height"></div>
    <div id="map" style='width: 100%; height: calc(100vh - 70px);'></div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({

      <!-- RAJOUTE le style de la carte dans le builder -->

      provider: {
      styles: [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-100},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-100},{"lightness":40}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-10},{"lightness":30}]},{"featureType":"landscape.man_made","elementType":"all","stylers":[{"visibility":"simplified"},{"saturation":-60},{"lightness":10}]},{"featureType":"landscape.natural","elementType":"all","stylers":[{"visibility":"simplified"},{"saturation":-60},{"lightness":60}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"},{"saturation":-100},{"lightness":60}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"},{"saturation":-100},{"lightness":60}]}]
    },
    <!-- Fin du style de la carte -->
      internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/cars/new.html.erb
<div class="spacer"></div>
<div class="container">
<h1>Ajoutez un véhicule</h1>
<%= render 'car_form' %>
</div>
<div class="spacer"></div>

app/views/cars/show.html.erb
<div class="spacer"></div>
<div class="container">
  <!-- FIRST COLUMN -->
  <div class="col-xs-12 col-sm-8 no-padding">
    <div class="car-details-picture-container">
      <div class="banner text-center" style="background-image: url('<%= @car.picture %> ')">
        <div class="banner-shadow"></div>
        <div class="banner-content">
          <h1><%= @car.make %> <%= @car.model %></h1>
        </div>
      </div>
    </div>
    <div class="car-details-map-container">
      <div id="map" style='width: 760px; height: 300px;'></div>
      <p><i class="fa fa-map-marker"></i> Paris, France</p>
    </div>
    <div class="car-details-description-container">
      <h3>Description</h3>
      <p><%= @car.description %></p>
      <h3>Caractéristiques techniques</h3>
      <div class="col-xs-12 col-sm-6">
        <table class="car-details-description-table">
          <tbody>
            <tr>
              <td>Année</td>
              <td><%= @car.year %></td>
            </tr>
            <tr>
              <td>Moteur</td>
              <td><%= @car.motorisation %></td>
            </tr>
            <tr>
              <td>Boîte</td>
              <td><%= @car.gear_box %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-xs-12 col-sm-6">
        <table class="car-details-description-table">
          <tbody>
            <tr>
              <td>Places</td>
              <td><%= @car.seats %> places</td>
            </tr>
            <tr>
              <td>Consommation</td>
              <td><%= @car.gaz_consumption %>l / 100km</td>
            </tr>
            <tr>
              <td>Type</td>
              <td><%= @car.category %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <h3>Options et accessoires</h3>
      <div class="col-xs-12 col-sm-4">
        <div class="car-details-car-option">
          <i class="fa fa-check-square-o"></i>
          <span>Climatisation</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-check-square-o"></i>
          <span>Direction assistée</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Régulateur de vitesse</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-check-square-o"></i>
          <span>GPS</span>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Siège bébé</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Coffre de toit</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Porte-vélos</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Pneus neige</span>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Chaines</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-square-o"></i>
          <span>Porte-skis</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-check-square-o"></i>
          <span>Lecteur CD</span>
        </div>
        <div class="car-details-car-option">
          <i class="fa fa-check-square-o"></i>
          <span>Entrée audio / iPod</span>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
    </div>
  </div>

  <!-- SECOND COLUMN -->
  <div class="col-xs-12 col-sm-4 no-padding">
    <%= render 'bookings/shared/bookingform' %>
  </div>
</div>

<div>
  <% if current_user == @car.user %>
    <%= link_to "Edit", edit_car_path(@car), class: "btn btn-info" %>
    <%= link_to "Delete", car_path(@car), class: "btn btn-info", method: :delete, data: {confirm: "Are you sure ?"} %>
  <% end %>
  <%= link_to "Back", cars_path, class: "btn btn-danger" %>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({

      <!-- RAJOUTE le style de la carte dans le builder -->

      provider: {
      styles: [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-100},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-100},{"lightness":40}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"saturation":-10},{"lightness":30}]},{"featureType":"landscape.man_made","elementType":"all","stylers":[{"visibility":"simplified"},{"saturation":-60},{"lightness":10}]},{"featureType":"landscape.natural","elementType":"all","stylers":[{"visibility":"simplified"},{"saturation":-60},{"lightness":60}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"},{"saturation":-100},{"lightness":60}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"},{"saturation":-100},{"lightness":60}]}]
    },
    <!-- Fin du style de la carte -->
      internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);

        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/dashboard/index.html.erb
<div class="cars-container">
  <p>display cars</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || 'Deways' %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name='description'
          content='<%= (yield(:description) || '').squish %>'>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

      <%= yield %>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/sidebar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="spacer"></div>
<%= render 'shared/sidebar' %>
<div class="text-center">
  <h2>
    Bookings summary
  </h2>

  <ul>
      <%= @bookings.each do |booking| %>
    <li>
      <div class="post">

    <% car = Car.find(booking.car_id)%>
  <div class='post-body'>
    <h2>
      <%= booking.checkin_date %>
    </h2>
    <p>

      <%= car.model %>
    </p>
  </div>
  <div class='post-controls'>
    <i class="fa fa-bars post-control post-control-hidden"></i>
    <i class="fa fa-star post-control post-control-hidden"></i>
    <div class="post-control">

      </div>
    </div>
  </div>
</div>
        <% end %>
    </li>

  </ul>

</div>

app/views/pages/home.html.erb
<div class="video-banner">

  <div class="container-liquid wrapper">

    <div class="col-xs-12 video-banner-content text-centered">
      <h1>Location de voiture entre particuliers</h1>
      <p class="text-centered">Cherchez parmi plus de 26 000 voitures et utilitaires de particuliers à louer dans toute la France</p>






      <%= form_tag(cars_path, :method => "get", class: "navbar-form", id: "search-form") do %>
          <div class="input-append">
            <div class="col-xs-12 text-center">
              <%= text_field_tag :place, params[:place], type:"address", class: "form-control form-round", placeholder: "ex: Paris" %>
              <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
                   of using a Rails form helper -->
              <button class="btn video-banner-btn margin-left" type="submit">Rechercher</button>
            </div>
          </div>
      <% end %>
    </div>

  </div>

  <div class="video-banner-container">
    <video autoplay muted poster="" id="bgvid" loop class="video-banner-video-fullscreen">
      <source src='<%= video_path("bg_video.mp4") %>' type="video/mp4">
      <source src='<%= video_path("bg_video.mp4") %>' type="video/webm">
    </video>
  </div>

  <div class="video-banner-gradient"></div>
</div>

app/views/shared/_car_card.html.erb
<div class="card-container">
  <div class="card">
  <%= link_to car_path(car) do %>
  <span class="card-link"></span>
    <span class="card-bg" style="background-image: url('<%= car.picture %> ')"></span>
    <span class="card-shadow"></span>
    <!-- <span class="card-description">Popular</span> -->
    <span class="card-text">
      <h2><%= car.make %> <%= car.model %></h2>
      <p><%= car.motorisation %> - <%= car.seats %> seats</p>
    </span>
  <% end %>
  </div>
  <span class="card-user">
    <ul class="list-inline">
      <li><p><%= car.user.first_name %> <%= car.user.last_name.first %>.</p></li>
      <li><%= image_tag car.user.picture.url(:thumb), class:"avatar avatar-large avatar-xl-bordered"%></li>
    </ul>
  </span>
  <span class="card-price">
      <%= car.daily_rate.to_i %>€<span class="card-price-day"> / jour</span>
  </span>
<!--   <span class="inline">
  <span class="ratings">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
      <i class="fa fa-star-o"></i>
      (16)
  </span>
  </span> -->
</span>


</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon navbar-wagon-fixed">

  <div class="container navbar-wagon-container">
    <!-- <div id= 'left-position'> -->

    <%= link_to root_path do %>
      <%= image_tag "logo.png", id: 'logo'%>
    <% end %>

    <hr>
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="navbar-wagon-username"><%= current_user.first_name.capitalize %></span><%= image_tag current_user.picture.url(:thumb), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to pages_dashboard_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>


    <%= link_to t(".top_call_to_action", default: "Ajouter une voiture"), new_car_path, class: "navbar-wagon-item navbar-wagon-button btn" %>


  </div>
</nav>